{
  description = "exigent-heron dev shell: JDK, Kotlin, Gradle, Android SDK. No Android Studio required.";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
          config.android_sdk.accept_license = true;
        };

        # Pinned SDK components. Bump these together (and re-check
        # compileSdk/targetSdk in app/build.gradle.kts) rather than
        # tracking "latest", so the shell stays reproducible between
        # `nix flake update` runs.
        androidComposition = pkgs.androidenv.composeAndroidPackages {
          cmdLineToolsVersion = "22.0";
          platformToolsVersion = "37.0.1";
          buildToolsVersions = [ "37.0.0" ];
          platformVersions = [ "37.0" ];
          includeEmulator = false;
          includeSystemImages = false;
          includeSources = false;
          includeNDK = false;
        };
        androidSdk = androidComposition.androidsdk;
        androidSdkRoot = "${androidSdk}/libexec/android-sdk";

        jdk = pkgs.jdk21;
      in
      {
        devShells.default = pkgs.mkShell {
          packages = [
            jdk
            pkgs.kotlin
            pkgs.gradle_9
            androidSdk
          ];

          JAVA_HOME = jdk.home;
          ANDROID_HOME = androidSdkRoot;
          ANDROID_SDK_ROOT = androidSdkRoot;

          shellHook = ''
            # AGP resolves aapt2 from Maven by default, and that binary
            # isn't patched for NixOS's linker layout. Point it at the
            # already-patched copy in the Nix-built SDK instead.
            # (This is nixpkgs's own recommended pattern — see
            # pkgs/development/mobile/androidenv/examples/shell.nix.)
            export GRADLE_OPTS="-Dorg.gradle.project.android.aapt2FromMavenOverride=$(echo "$ANDROID_HOME/build-tools/"*"/aapt2")"

            # local.properties is gitignored and machine-specific; regenerate
            # it every time the shell starts so editors/IDEs that look for
            # sdk.dir keep working without anyone hand-maintaining it.
            cat > local.properties <<EOF
            # Generated by 'nix develop' — do not edit, do not commit.
            sdk.dir=$ANDROID_HOME
            EOF

            echo "exigent-heron dev shell"
            echo "  java:   $(java -version 2>&1 | head -n1)"
            echo "  kotlin: $(kotlinc -version 2>&1 | tail -n1)"
            echo "  gradle: $(gradle --version | grep -m1 Gradle)"
            echo "  sdk:    $ANDROID_HOME"
            echo
            echo "No gradlew in this repo by design — use the 'gradle' on PATH,"
            echo "e.g. 'gradle assembleDebug' or 'gradle testDebugUnitTest'."
          '';
        };
      }
    );
}
